### Blog de julio
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGx5IiwiaWQiOiI2NzZiNjViNGFhM2RiNDhmN2Q1OWQ5NDMiLCJpYXQiOjE3MzUxMzg1OTZ9.B-OzPOC2kMjpTQE3IwlOVmsIHe2YWwLB0mS4VwIzzyA

{
    "title": "blog de Sergio",
    "author": "Sergio",
    "url": "sergio.com"
}

### Blog de kelly
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGx5IiwiaWQiOiI2NzZiNjViNGFhM2RiNDhmN2Q1OWQ5NDMiLCJpYXQiOjE3MzUxMzg1OTZ9.B-OzPOC2kMjpTQE3IwlOVmsIHe2YWwLB0mS4VwIzzyA

{
    "title": "probando put",
    "author": "probano put",
    "url": "probando put",
    "likes": 400
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": 300
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": 400
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": 500
}
