POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikp1bGlvIiwiaWQiOiI2Njg0ZDAzM2U1ZTczNmQyY2NmNTYzZGMiLCJpYXQiOjE3MjgwNDExMDd9.mrme8P9A_RqB3ADbzFw7kyLhq2Cw0nKGCjciw1imLdo

{
    "title": "otro blog",
    "author": "otro",
    "url": "otro.com"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtlbGx5IiwiaWQiOiI2NmZlODJhYzRmNmM2YWQzZjhjZjhjYTIiLCJpYXQiOjE3Mjc5NTU2NDN9.Vg7VqC1HioYNWCCrwyRuo8lse-1CnShORn_vQnnGCUI

{
    "title": "test2",
    "author": "test",
    "url": "test",
    "likes": 200
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": 300
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": 400
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": 500
}
